AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Description: A very simple demo to demonstrate Websockets on the API Gateway

Parameters:
  TableName:
    Type: String
    Default: 'demo_api_connections'
    Description: (Required) The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'

Resources:
  ScheduledResponderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda_handlers/
      Runtime: python3.7
      Handler: scheduled_handler.handle_trigger
      Environment:
        Variables:
          CONNECTIONS_TABLE_NAME: !Ref TableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
#      Events:
#        Regularly:
#          Type: Schedule
#          Properties:
#            Schedule: rate(1 minute)

  ScheduledResponderPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - "ScheduledResponderFunction"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ScheduledResponderFunction
      Principal: lambda.amazonaws.com

  # A single function to handle the API Gateway routes
  DefaultHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda_handlers/
      Runtime: python3.7
      Handler: handler.handle_gateway_request
      Environment:
        Variables:
          CONNECTIONS_TABLE_NAME: !Ref TableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName

  # Note that the API Gateway has the WEBSOCKET protocol
  DemoAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: DemoAPI
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  # We need 3 routes for the Websocket gateway to function:
  # The $connect route, which is called while a websocket connection is set up
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DemoAPI
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DefaultIntegration

  # The $disconnect route, which is called automatically when the websocket connection is closed.
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DemoAPI
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DefaultIntegration

  # The $default route, which is called for every other message not matching the RouteSelectionExpression of the API.
  # For this demo, this route will be used to schedule events. Normally, you could add distinct routes for actions,
  # e.g. with a RouteKey of 'schedule'.
  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DemoAPI
      RouteKey: $default
      AuthorizationType: NONE
      OperationName: DefaultRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DefaultIntegration

  DefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DemoAPI
      Description: A default integration that's called for all routes
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DefaultHandlerFunction.Arn}/invocations

  HandlerPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - "DefaultHandlerFunction"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DefaultHandlerFunction
      Principal: apigateway.amazonaws.com

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref DemoAPI
    DependsOn:
      - ConnectRoute
      - DisconnectRoute

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref DemoAPI
      DeploymentId: !Ref Deployment
      StageName: Dev
      Description: Dev Stage
      DefaultRouteSettings:
        LoggingLevel: "INFO"

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "connectionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "connectionId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref TableName


Outputs:
  ConnectionsTableArn:
    Description: "Connections table ARN"
    Value: !GetAtt ConnectionsTable.Arn

  OnConnectFunctionArn:
    Description: "OnConnect function ARN"
    Value: "DefaultHandlerFunction"

  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Join [ '', [ 'wss://', !Ref DemoAPI, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]

